import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SidebarPage from "@/components/sidebar/Sidebar";
import { Toaster } from "@/components/ui/sonner";
import { Providers } from "./providers"; // ✅ import

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Deadstock Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers> {/* ✅ wrap here */}
          <Toaster position="top-right" richColors />
          
          <SidebarPage>
            {children}
          </SidebarPage>
          
        </Providers>
      </body>
    </html>
  );
}